# frozen_string_literal: true

# Generated by OpenAPI Generator (https://openapi-generator.tech)
# OpenAPI spec version: 2.9.0 | Generator version: 7.20.0

$:.push File.expand_path("../lib", __FILE__)
require "lunchmoney-sdk-ruby/version"

Gem::Specification.new do |s|
  s.name        = "lunchmoney-sdk-ruby"
  s.version     = LunchMoney::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Ajaya Agrawalla"]
  s.email       = ["ajaya@clearstack.io"]
  s.homepage    = "https://github.com/ajaya/lunchmoney-sdk-ruby"
  s.summary     = "Ruby SDK for the Lunch Money API v2"
  s.description = "Ruby client for the Lunch Money v2 API. Manage transactions, budgets, categories, accounts, tags, and more. Auto-generated from the official OpenAPI spec."
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.4"

  s.metadata = {
    "homepage_uri"      => s.homepage,
    "source_code_uri"   => "https://github.com/ajaya/lunchmoney-sdk-ruby",
    "changelog_uri"     => "https://github.com/ajaya/lunchmoney-sdk-ruby/blob/main/CHANGELOG.md",
    "bug_tracker_uri"   => "https://github.com/ajaya/lunchmoney-sdk-ruby/issues",
    "documentation_uri" => "https://rubydoc.info/gems/lunchmoney-sdk-ruby",
    "rubygems_mfa_required" => "true"
  }

  s.add_runtime_dependency 'httpx', '~> 1.0', '>= 1.0.0'
  s.add_runtime_dependency 'logger'

  s.add_development_dependency 'rake', '~> 13.3'
  s.add_development_dependency 'rspec', '~> 3.13'
  s.add_development_dependency 'pry-byebug', '~> 3.12'
  s.add_development_dependency 'rubocop', '~> 1.85'

  s.files         = Dir["lib/**/*", "docs/**/*", "LICENSE", "README.md", "CHANGELOG.md"].select { |f| File.file?(f) }
  s.executables   = []
  s.require_paths = ["lib"]
end
